### ISSUE TITLE
the webUI is empty

### ISSUE THREAD

**Issue by zzhangpurdue** [hleb-albau/kafka-manager-docker#17]
I keep getting the following logs
`kafka-manager_1    | 2019-11-06 08:58:30,672 - [INFO] k.m.a.KafkaManagerActor - Updating internal state...`

my docker-compose.yml is 
```
version: "3.3"
  
services:
  spark-streaming:
    container_name: "spark-streaming"
    build:
      context: .
      dockerfile: Spark.Dockerfile
    environment:
      - SOURCE_TOPIC=analyzer
      - TARGET_TOPIC=average
      - KAFKA_BROKER=kafka:9092
      - BATCH_DURATION=5
    restart: on-failure
    depends_on:
      - kafka
    networks:
      - kafka-spark-streaming

  producer:
    container_name: "producer"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TARGET_TOPIC=analyzer
      - KAFKA_BROKER=kafka:9092
      - SYMBOL=BTC-USD
    restart: on-failure
    depends_on:
      - kafka
    networks:
      - kafka-spark-streaming

  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    environment:
      - ZK_HOSTS=zookeeper:2181
      - APPLICATION_SECRET="random-secret"
    ports:
      - 9000:9000
    networks:
      - kafka-spark-streaming

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - kafka-spark-streaming

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - JMX_PORT=9999
    networks:
      - kafka-spark-streaming

networks:
  kafka-spark-streaming:
```

everything is working except the empty webUI. 
any idea?
![image](https://user-images.githubusercontent.com/5746653/68283845-467f8980-00b7-11ea-9f5b-f5a1fadbb74d.png)

**Comment by hleb-albau** [comment]
hi @zzclynn
Some sort of bad ux here. There is no auto-discovery (see https://github.com/yahoo/kafka-manager/issues/244) for Kafka clusters. You should add it manualy using top left **Cluster** menu.
![image](https://user-images.githubusercontent.com/2991991/68337551-cd515800-00f1-11ea-91a8-b4ab02887a57.png)

Btw, I suggest you to use confluentinc kafka image
```
version: "3.3"
volumes:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
  kafka_log:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    container_name:  zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"  # use kafka:29092 to access kafka from docker network
      - "9092:9092"    # use localhost:9092 to access kafka from host machine
      - "19092:19092"  # use internal.io:19092 to access kafka from internal network
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: LISTEN_DOCKER_NETWORK://kafka:29092,LISTEN_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTEN_DOCKER_NETWORK:PLAINTEXT,LISTEN_HOST:PLAINTEXTT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTEN_DOCKER_NETWORK
    volumes:
      - kafka_data:/var/lib/kafka/data
      - kafka_log:/var/lib/kafka/log

  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:5.3.0
    container_name: kafka-rest-proxy
    restart: on-failure
    depends_on:
      - kafka
    environment:
      KAFKA_REST_LISTENERS: http://kafka-rest-proxy:8082
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:29092

  kafka-topics-ui:
    image: landoop/kafka-topics-ui
    container_name: kafka-topics-ui
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - kafka-rest-proxy
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082/"
      RECORD_POLL_TIMEOUT: 30000
      PROXY: "true"
```
