### ISSUE TITLE
add default cluster configuration via env variables

### ISSUE THREAD

**Issue by hleb-albau** [hleb-albau/kafka-manager-docker#25]
There is no good way to provide kafka manager default cluster config, rather than manually using webui.
We can create same hack as described there(https://github.com/yahoo/CMAK/issues/244#issuecomment-461242965), and add ability to specify default cluster config via env variables.  

Also, update readme.md with description of new functionality.

**Comment by martinmalek** [comment]
I solve it using a job. Synching the job to run after cluster availability could be one improvement.

```
apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-cluster
  namespace: kafka-cluster
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: create-kafka-cluster
        image: radial/busyboxplus:curl
        command: ["/bin/sh", "-c", "curl --insecure https://<your-kafka-manager-address>/clusters --data 'name=<your-cluster-name>&zkHosts=<your-zk-address:port>&kafkaVersion=2.4.0&jmxEnabled=true&jmxUser=&jmxPass=&pollConsumers=true&activeOffsetCacheEnabled=true&tuning.brokerViewUpdatePeriodSeconds=30&tuning.clusterManagerThreadPoolSize=2&tuning.clusterManagerThreadPoolQueueSize=100&tuning.kafkaCommandThreadPoolSize=2&tuning.kafkaCommandThreadPoolQueueSize=100&tuning.logkafkaCommandThreadPoolSize=2&tuning.logkafkaCommandThreadPoolQueueSize=100&tuning.logkafkaUpdatePeriodSeconds=30&tuning.partitionOffsetCacheTimeoutSecs=5&tuning.brokerViewThreadPoolSize=4&tuning.brokerViewThreadPoolQueueSize=1000&tuning.offsetCacheThreadPoolSize=4&tuning.offsetCacheThreadPoolQueueSize=1000&tuning.kafkaAdminClientThreadPoolSize=4&tuning.kafkaAdminClientThreadPoolQueueSize=1000&tuning.kafkaManagedOffsetMetadataCheckMillis=30000&tuning.kafkaManagedOffsetGroupCacheSize=1000000&tuning.kafkaManagedOffsetGroupExpireDays=7&securityProtocol=PLAINTEXT&saslMechanism=DEFAULT' -X POST"]
      restartPolicy: Never
```
