### ISSUE TITLE
Too long startup time?

### ISSUE THREAD

**Issue by zengxc-1996** [hleb-albau/kafka-manager-docker#33]
```
when I start your docker images,It need more than 5mins to access the page;
I have a good suggestion,
change this file:
/usr/local/openjdk-11/conf/security/java.security
securerandom.source=file:/dev/random   to  securerandom.source=file:/dev/urandom,
It starts right away
```
Looking forward to further communication;

**Comment by hleb-albau** [comment]
Seems we can  just use`-Dsecurerandom.source=file:/dev/urandom` option in cmd. Feel free to provide PR, to add it to entrypoint.

**Comment by zengxc-1996** [comment]
Thanks for your help,But I didn't go well
when I run this images and add -Dsecurerandom.source to my compose file ,it's works,
but I reboot my ecs 
![image](https://user-images.githubusercontent.com/63622990/109744432-3de88600-7c0d-11eb-93f2-452374d2d076.png)
I can't open the page;
docker logs cmak:
![image](https://user-images.githubusercontent.com/63622990/109743731-26f56400-7c0c-11eb-9ab2-c45bc5e160da.png)
I don't know what to do,
it's my docker-composer.yml:
```
version: '3.6'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: "cmak"
    restart: always
    ports:
      - "9005:9000"
    command:
      - "-Dcmak.zkhosts=172.17.0.1:2181"
      - "-DbasicAuthentication.enabled=true"
      - "-DbasicAuthentication.username=username"
      - "-DbasicAuthentication.password=password123"
      - "-Dsecurerandom.source=file:/dev/./urandom"
```
